### ISSUE TITLE
why we need a new Data in WidgetForm

### ISSUE THREAD

**Issue by mntxwall** [playframework/play-scala-forms-example#35]
hi i am new in play framework.
what's the different between Data in WidgetForm and Widget in model?
i combine them in a new project, and it works fine.

**Comment by wsargent** [comment]
It's described in the documentation page for forms: https://www.playframework.com/documentation/2.6.x/ScalaForms

> 
> You are not limited to using case classes in your form mapping. As long as the apply and unapply methods are properly mapped, you can pass in anything you like, such as tuples using the Forms.tuple mapping or model case classes. However, there are several advantages to defining a case class specifically for a form:
> 
> * Form specific case classes are convenient. Case classes are designed to be simple containers of data, and provide out of the box features that are a natural match with Form functionality.
> 
> * Form specific case classes are powerful. Tuples are convenient to use, but do not allow for custom apply or unapply methods, and can only reference contained data by arity (_1, _2, etc.)
> 
> * Form specific case classes are targeted specifically to the Form. Reusing model case classes can be convenient, but often models will contain additional domain logic and even persistence details that can lead to tight coupling. In addition, if there is not a direct 1:1 mapping between the form and the model, then sensitive fields must be explicitly ignored to prevent a parameter tampering attack.

**Comment by wsargent** [comment]
This is also referenced directly in the comments for WidgetForm:

> Using a class specifically for form binding reduces the chances of a parameter tampering attack and makes code clearer.

https://github.com/playframework/play-scala-forms-example/blob/2.6.x/app/controllers/WidgetForm.scala#L10

**Comment by wsargent** [comment]
Also see the guardian article linked from the README:

https://www.theguardian.com/info/developer-blog/2015/dec/30/how-to-add-a-form-to-a-play-application
